project_name: persisto

builds:
  - id: persisto
    main: ./src/main.go
    binary: persisto

    flags:
      - -trimpath
      - -mod=readonly

    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
      - -X main.BuildTime={{.Date}}
      - -X main.GitCommit={{.FullCommit}}

    env:
      - CGO_ENABLED=0

    goos:
      - linux
      - darwin
      - windows

    goarch:
      - amd64
      - arm64

    ignore:
      - goos: windows
        goarch: arm64

archives:
  - id: default
    builds:
      - persisto

    name_template: >-
      {{ .Env.GITHUB_REPOSITORY_NAME }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

    format_overrides:
      - goos: windows
        format: zip

    files:
      - README.md
      - LICENSE*
      - CHANGELOG*

snapshot:
  name_template: "{{ incpatch .Version }}-next"

release:
  github:
    owner: "{{ .Env.GITHUB_REPOSITORY_OWNER }}"
    name: "{{ .Env.GITHUB_REPOSITORY_NAME }}"

  header: |
    ## Release {{ .Tag }} ({{ .Date }})

    Welcome to this new release of Persisto!  footer: |
    ## Installation

    Download the binary for your platform from the assets below.

    **Full Changelog**: https://github.com/USER/persisto/compare/{{ .PreviousTag }}...{{ .Tag }}

  draft: false

  prerelease: auto

  name_template: "Release {{.Tag}}"

changelog:
  use: github
  sort: asc

  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: "Bug fixes"
      regexp: '^.*?bug(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: "Performance improvements"
      regexp: '^.*?perf(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: "Refactors"
      regexp: '^.*?refactor(\([[:word:]]+\))??!?:.+$'
      order: 3
    - title: "Documentation updates"
      regexp: '^.*?docs(\([[:word:]]+\))??!?:.+$'
      order: 4
    - title: Others
      order: 999

  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"
      - typo
      - Merge pull request
      - Merge branch

universal_binaries:
  - replace: true
    name_template: "{{ .Env.GITHUB_REPOSITORY_NAME }}"

before:
  hooks:
    - go mod tidy
    - go generate ./...

metadata:
  mod_timestamp: "{{ .CommitTimestamp }}"
