version: "3.8"

services:
  persisto:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
    volumes:
      - ./storage:/app/storage
    restart: unless-stopped
