name: release pipeline

on:
  push:
    tags: ["v*"]

permissions:
  contents: write
  packages: write
  id-token: write

jobs:
  pre-release-checks:
    name: pre-release checks
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: setup go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"

      - name: cache go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: install development tools
        run: make install-tools

      - name: run ci checks
        run: make ci

      - name: check go-releaser configuration
        run: make goreleaser-check

  release:
    name: release
    runs-on: ubuntu-latest
    needs: pre-release-checks

    steps:
      - name: checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"

      - name: setup docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: login in to GCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: install development tools
        run: make install-tools

      - name: run go-register
        run: make goreleaser-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
