name: snapshot build pipeline

on:
  push:
    branches: [main]

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  pre-snapshot-checks:
    name: pre-snapshot checks
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: setup go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true

      - name: install development tools
        run: make install-tools

      - run: make build
      - run: make test
      - run: make lint

      - name: check go-releaser configuration
        run: make goreleaser-check

  snapshot:
    name: snapshot build
    runs-on: ubuntu-latest
    needs: pre-snapshot-checks

    steps:
      - name: checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true

      - name: setup docker buildx
        uses: docker/setup-buildx-action@v3

      - name: login to GCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: install development tools
        run: make install-tools

      - name: run go-releaser (Snapshot)
        run: make goreleaser-snapshot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}

      - name: upload snapshot artifacts
        uses: actions/upload-artifact@v4
        with:
          name: snapshot-dist-${{ github.sha }}
          path: dist/
